config/routes.rb
VolunteerTracker::Application.routes.draw do

  # PUBLIC FACING
  resources :departments, only: [:index, :show]
  resources :charities, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }

  resources :users, only: [:edit] do
    resources :user_availabilities, only: [:index, :create, :destroy]
    resources :subaccounts do
      post :import, on: :collection
    end
  end

  get '/welcome' => 'welcome#index'

  namespace :admin do
    resources :users
    resources :charities
    resources :departments
    resources :events
    resources :organisations
    resources :department_managers
    resources :department_assistants do
      member { post :restrict_blocks }
      member { get :show_modal }
    end
    root to: 'base#index'
  end

  resources :dashboard, only: [:index, :registration_complete]
  namespace :dashboard do
    # VIEWING ONLY
    resources :departments, only: [:show, :edit] do
      member do
        get :for_promote
        get :assistants
      end
    end
    resources :user_charities

    # ROLES
    resources :department_assistants, only: [:create, :destroy, :restrict]
    resources :volunteer_managers, only: [:create, :destroy]
    resources :users

    # TIME RELATED
    resources :days
    resources :users do
      resources :user_availabilities
      resources :user_charities
    end
    resources :user_availabilities
    resources :department_blocks

    resources :user_schedules do
      get :dymo, on: :member
    end


    resources :become_users do
      collection do
        get :accept_transfer
        get :decline_transfer
        get :get_user_list
      end
    end

    resources :events do
      get :calendar, on: :collection
    end

    resources :check_ins do
      collection do
        get :scheduled
        get :manage
        get :active
        get :inactive
        get :fastpass
        get :manage
        put :update_batch
        post :create_batch
        post :is_accessible
      end
    end
    get 'volunteers/:year/:month/:day' => 'volunteers#index'

    get 'check_ins/scheduled/:day_id' => "check_ins#scheduled"
    get 'check_ins/active/:day_id' => "check_ins#active"
    get 'check_ins/inactive/:day_id' => "check_ins#inactive"

    get 'volunteers/:day_id' => "volunteers#index", as: :volunteers

    get 'check_outs/fastpass' => "check_ins#fastpass_out", as: :fastpass_check_out
    post 'check_outs' => "check_ins#check_out", as: :check_out

    resources :flags

    get 'department_blocks/:id/copy/' => 'department_blocks#copy'
    get 'departments/:id/export/:year/:month/:day' => 'department_blocks#export'
    get 'departments/:id/schedule/:year/:month/:day' => 'departments#schedule'
  end

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :root
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  resourcify

  has_many :days, dependent: :destroy
  belongs_to :user, primary_key: :assigned_to, foreign_key: :id
  belongs_to :organisation

  validates :name, :route_type, :day_of_start, :day_of_finish, :organisation_id, presence: true
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < Admin::BaseController
  before_action :event, only: [:show, :edit, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: EventDatatable.new(view_context) }
    end
  end

  def show
  end

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    service = EventsService.new(as: current_user)
    @event = service.create(event_params)

    respond_to do |format|
      if @event.persisted?
        format.html { redirect_to [:admin, @event], flash: { success: 'Event was successfully created.' } }
        format.json { render :show, status: :created, location: [:admin, @event] }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    service = EventsService.new(as: current_user)
    @event = service.update(params[:id], event_params)

    respond_to do |format|
      if @event.errors.empty?
        format.html { redirect_to [:admin, @event], flash: { success: 'Event was successfully updated.' } }
        format.json { render :show, status: :ok, location: [:admin, @event] }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to admin_root_url(anchor: 'events'), flash: { success: 'Event was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private
    def event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit!
    end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < DashboardController

  def calendar
    @events = Event.all
    respond_to do |format|
      format.html
      format.json { render json: @events }
    end
  end

end

app/views/admin/events/_form.html.slim
= simple_form_for([:admin, @event], html: {class: 'form-horizontal'}) do |f|
  .container-fluid
    .col-sm-8.col-sm-offset-2
      = f.input :name
      = f.input :organisation_id, collection: Organisation.all.map { |r| [r.name, r.id] }, include_blank: false
      = f.input :assigned_to, collection: User.with_role(:event_admin).map { |r| [r.full_name, r.id] }
      = f.input :route_type, collection: [1, 2, 3], include_blank: false
      = f.input :address_line_1
      = f.input :address_line_2
      = f.input :city
      = f.input :state
      = f.input :zip
      = f.input :other, as: :text, input_html: { cols: 50, rows: 3 }
      .form-group class=("error" if @event.errors[:day_of_start].any?)
        = f.label "Event duration"
        .controls.input-daterange
          = f.input_field :day_of_start, as: :string, class: 'form-control'
          span.add-on to
          = f.input_field :day_of_finish, as: :string, class: 'form-control'
          span.help-inline
            = f.error :day_of_start
      = f.input :days_for_setup
      = f.input :days_for_tear_down
      .form-group
        .col-sm-9.col-sm-offset-3
          = f.button :submit, class: 'btn btn-primary'

app/views/admin/events/edit.html.slim
.page-header
  h1 Edit Event

= render 'form'

app/views/admin/events/edit.js.erb
//  Select the elements for re-use
$modal = $('.edit-modal');
$title = $modal.find('.modal-title');
$body = $modal.find('.modal-body');

// Set the title of the modal to an instance-relevant title
title = 'Editing Event';

// Render the form and store in a variable
body = '<%= j render "form" %>';

// Set the modal's title and body to the above values
$title.html(title);
$body.html(body);

// Hide the submit button (it'd be a duplicate) and make the form remote
$body.find('input[type="submit"]').hide();
$body.find('form').attr('data-remote', 'true');
$body.find('.input-daterange').datepicker({ format: 'yyyy-mm-dd' });

// Display the modal
$modal.modal();

app/views/admin/events/new.html.slim
.page-header
  h1 New Event

= render 'form'

app/views/admin/events/show.html.slim
.page-header
  h1 = @event.name

= link_to 'Back', admin_root_url(anchor: 'events'), class: 'btn btn-default'
'
= link_to 'Edit', edit_admin_event_path(@event), class: 'btn btn-primary'
'
= link_to 'Delete', admin_event_path(@event), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/events/update.js.erb
// Select the elements for re-use
$modal = $('.edit-modal');
$body = $modal.find('.modal-body');

// Remove any past alerts and put a new alert in
$body.find('.alert').remove();
$body.append('<div class="alert alert-success"><p>Changes saved! You may now close this window.</p></div>');

window.adminEventTable.fnDraw();