config/routes.rb
VolunteerTracker::Application.routes.draw do

  # PUBLIC FACING
  resources :departments, only: [:index, :show]
  resources :charities, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }

  resources :users, only: [:edit] do
    resources :user_availabilities, only: [:index, :create, :destroy]
    resources :subaccounts do
      post :import, on: :collection
    end
  end

  get '/welcome' => 'welcome#index'

  namespace :admin do
    resources :users
    resources :charities
    resources :departments
    resources :events
    resources :organisations
    resources :department_managers
    resources :department_assistants do
      member { post :restrict_blocks }
      member { get :show_modal }
    end
    root to: 'base#index'
  end

  resources :dashboard, only: [:index, :registration_complete]
  namespace :dashboard do
    # VIEWING ONLY
    resources :departments, only: [:show, :edit] do
      member do
        get :for_promote
        get :assistants
      end
    end
    resources :user_charities

    # ROLES
    resources :department_assistants, only: [:create, :destroy, :restrict]
    resources :volunteer_managers, only: [:create, :destroy]
    resources :users

    # TIME RELATED
    resources :days
    resources :users do
      resources :user_availabilities
      resources :user_charities
    end
    resources :user_availabilities
    resources :department_blocks

    resources :user_schedules do
      get :dymo, on: :member
    end


    resources :become_users do
      collection do
        get :accept_transfer
        get :decline_transfer
        get :get_user_list
      end
    end

    resources :events do
      get :calendar, on: :collection
    end

    resources :check_ins do
      collection do
        get :scheduled
        get :manage
        get :active
        get :inactive
        get :fastpass
        get :manage
        put :update_batch
        post :create_batch
        post :is_accessible
      end
    end
    get 'volunteers/:year/:month/:day' => 'volunteers#index'

    get 'check_ins/scheduled/:day_id' => "check_ins#scheduled"
    get 'check_ins/active/:day_id' => "check_ins#active"
    get 'check_ins/inactive/:day_id' => "check_ins#inactive"

    get 'volunteers/:day_id' => "volunteers#index", as: :volunteers

    get 'check_outs/fastpass' => "check_ins#fastpass_out", as: :fastpass_check_out
    post 'check_outs' => "check_ins#check_out", as: :check_out

    resources :flags

    get 'department_blocks/:id/copy/' => 'department_blocks#copy'
    get 'departments/:id/export/:year/:month/:day' => 'department_blocks#export'
    get 'departments/:id/schedule/:year/:month/:day' => 'departments#schedule'
  end

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :root
    end
  end
end

app/models/department.rb
class Department < ActiveRecord::Base
  resourcify
	has_many :department_managers
	has_many :department_assistants

	has_many :department_blocks

	def estimated_hours
		total = 0
		self.department_blocks.each do |department_block|
			start_time = Time.parse(department_block.start_time)
			end_time = Time.parse(department_block.end_time)

			duration_in_minutes = (end_time - start_time) / 60
			duration_in_hours = duration_in_minutes / 60

			if department_block.suggested_number_of_workers
				total += department_block.suggested_number_of_workers * duration_in_hours
			end
		end
		return total
	end

	def total_department_block_slots
		count = 0
		self.department_blocks.each do |department_block|
			count = count + department_block.suggested_number_of_workers.to_i
		end
		count
	end

	def scheduled_department_block_slots
		count = 0
		self.department_blocks.each do |department_block|
			count = count + department_block.user_schedules.length
		end
		count
	end
end

app/controllers/admin/departments_controller.rb
class Admin::DepartmentsController < Admin::BaseController
  before_action :department, only: [:show, :edit, :update, :destroy]

  def index
    respond_to do |format|
      format.html
      format.json { render json: DepartmentDatatable.new(view_context) }
    end
  end

  def show
    @department_managers = User.includes(:department_manager).where(role: "department_manager")
    @department_managers.select!{|user| user.department_manager.nil? }


    @department_assistants = User.includes(:department_assistant).where(role: "department_assistant")
    @department_assistants.select!{|user| user.department_assistant.nil? }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  def new
    @department = Department.new
  end

  def edit
    @department_manager = DepartmentManager.new
  end

  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to [:admin, @department], flash: { success: 'Department was successfully created.' } }
        format.json { render json: @department, status: :created, location: [:admin, @department] }
      else
        format.html { render action: "new" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @department.update_attributes(department_params)
        format.html { redirect_to [:admin, @department], flash: { success: 'Department was successfully updated.' } }
        format.json { head :no_content }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @department.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to admin_root_url(anchor: 'departments'), flash: { success: 'Department was successfully destroyed.' } }
      format.json { head :no_content }
    end
  end

  private
    def department
      @department = Department.find(params[:id])
    end

    def department_params
      params.require(:department).permit!
    end

end

app/controllers/dashboard/departments_controller.rb
class Dashboard::DepartmentsController < DashboardController
  DEFAULT_PER_PAGE = 10
  before_filter :prepare_scope, only: [:for_promote, :assistants, :edit]
  before_filter :load_department, only: [:assistants, :edit]

  def show
    service = DepartmentService.new
    select = OpenStruct.new(
      total_slots: true,
      estimate_hours: true,
      scheduled_count: true
    )

    @department = service.prepare_single(select, params[:id])
    @department_block = DepartmentBlock.new
    @volunteer_hours = service.volunteer_hours_progress(@department.id)
    @days = Day.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  def edit
    @department_assistant = DepartmentAssistant.new
    @users = service.users_for_promote(@scope)
    @department_assistants = service.assistans_for_assignment(@scope)
    @department_blocks = service.blocks_for_assignment(params[:id])
  end

  def for_promote
    @users = service.users_for_promote(@scope)
  end

  def assistants
    @assistants = service.assistans_for_assignment(@scope)
  end

  def schedule
    @department = Department.find(params[:id])
    @department_block = DepartmentBlock.new()
    @days = Day.all
    @day = Day.where("year = ? AND month = ? AND mday = ?", params[:year],params[:month],params[:day]).first
    render layout: false
  end

  private
    # TODO: implement via datatables
    def prepare_scope
      @scope = {
        per: (params[:per] || DEFAULT_PER_PAGE).to_i,
        page: (params[:page] || 1).to_i,
        order_name: params[:order_name],
        order_role: params[:order_role],
        q: params[:q]
      }
    end

    def service
      @service ||= DepartmentService.new(as: current_user)
    end

    def load_department
      @department = Department.find(params[:id])
    end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    @departments = Department.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departments }
    end
  end

  def show
    @department = Department.find(params[:id])
    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  def new
    @department = Department.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @department }
    end
  end

  def edit
    @department = Department.find(params[:id])
  end

  def create
    @department = Department.new(params[:department])

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, flash: { success: 'Department was successfully created.' } }
        format.json { render json: @department, status: :created, location: @department }
      else
        format.html { render action: 'new' }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @department = Department.find(params[:id])

    respond_to do |format|
      if @department.update_attributes(params[:department])
        format.html { redirect_to @department, flash: { success: 'Department was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department = Department.find(params[:id])
    @department.destroy

    respond_to do |format|
      format.html { redirect_to departments_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/dashboard/departments_helper.rb
module Dashboard::DepartmentsHelper
  def get_estimated_hours(department_id)
    @department = Department.find(department_id)
    total = 0
    @department.department_blocks.each do |department_block|
      start_time = department_block.start_time.utc_date
      end_time = department_block.end_time.utc_date

      duration_in_minutes = (end_time.to_f - start_time) / 60 
      duration_in_hours = duration_in_minutes / 60

      if department_block.suggested_number_of_workers
        total += department_block.suggested_number_of_workers * duration_in_hours
      end
    end

    return total
  end


  def get_department_usage(estimated_hours, allocated_hours)
    if allocated_hours == 0
      return 100
    else
      return ( estimated_hours.to_f / allocated_hours.to_f ) * 100
    end
  end

  def get_department_usage_class(estimated_hours, allocated_hours)
    if estimated_hours.to_f > allocated_hours.to_f
      return "progress-bar-danger"
    else
      return ""
    end
  end
end

app/views/admin/departments/_assign_department_assistants_modal.html.slim
#assign_department_assistants.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h4.modal-title Assign Department Assistants
      .modal-body
        - if department_assistants.length == 0
          .alert.alert-error
            strong Warning!
            ' No Department Assistants Available. You need to promote a volunteer to the Department Assistant role before you can assign them to this department.
        - else
          p Here is a list of users you can add as a Department Assistant

          table.table.table-bordered.table-striped.dataTables
            thead
              th Name
              th Username
              th Assign as Department Assistant
            tbody
              - department_assistants.each do |user|
                tr
                  td= user.full_name
                  td= user.username
                  td
                    = simple_form_for [:admin, DepartmentAssistant.new], html: { data: { type: :json } } do |f|
                      = f.input :user_id, as: :hidden, input_html: { value: user.id }
                      = f.input :department_id, as: :hidden, input_html: { value: @department.id }
                      = f.button :submit, class: 'btn btn-success', input_html: { value: 'Assign' }

app/views/admin/departments/_assign_department_managers_modal.html.slim
#assign_department_managers.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h4.modal-title Assign Department Managers
      .modal-body
        - if department_managers.empty?
          .alert.alert-error
            strong Warning!
            ' No Department Managers Available. You need to promote a volunteer to the Department Manager role before you can assign them to this department.
        - else
          p Here is a list of users you can add as a Department Manager

          table.table.table-bordered.table-striped.dataTables
            thead
              th Name
              th Username
              th Assign as Department Manager
            tbody
              - department_managers.each do |user|
                tr
                  td= user.full_name
                  td= user.username
                  td
                    = simple_form_for [:admin, DepartmentManager.new], html: { data: { type: :json } } do |f|
                      = f.input :user_id, as: :hidden, input_html: { value: user.id }
                      = f.input :department_id, as: :hidden, input_html: { value: @department.id }
                      = f.button :submit, class: 'btn btn-success', input_html: { value: 'Assign' }

app/views/admin/departments/_form.html.slim
= simple_form_for([:admin, @department], html: {class: 'form-horizontal'}) do |f|
  .container-fluid
    .col-sm-8.col-sm-offset-2
      = f.input :name, as: :string
      = f.input :budgeted_hours
      = f.input :email, as: :string
      .form-group
        .col-sm-9.col-sm-offset-3
        = f.button :submit, class: 'btn btn-primary'

app/views/admin/departments/edit.html.slim
.page-header
  h1 Edit Department

= render 'form'

app/views/admin/departments/edit.js.erb
//  Select the elements for re-use
$modal = $('.edit-modal');
$title = $modal.find('.modal-title');
$body = $modal.find('.modal-body');

// Set the title of the modal to an instance-relevant title
title = 'Editing Department';

// Render the form and store in a variable
body = '<%= j render "form" %>';

// Set the modal's title and body to the above values
$title.html(title);
$body.html(body);

// Hide the submit button (it'd be a duplicate) and make the form remote
$body.find('input[type="submit"]').hide();
$body.find('form').attr('data-remote', 'true');

// Display the modal
$modal.modal();

app/views/admin/departments/new.html.slim
.page-header
  h1 New Department

= render 'form'

app/views/admin/departments/show.html.slim
.page-header
  .pull-right
    = link_to 'Back', admin_root_url(anchor: 'departments'), class: 'btn btn-default btn-sm'
    '
    = link_to 'Edit', edit_admin_department_path(@department), class: 'btn btn-primary btn-sm'
    '
    = link_to 'Delete', admin_department_path(@department), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?' }
  h1 = @department.name

p
  b Department Email:
  '
  = @department.email

p
  b Budgeted Hours:
  '
  = @department.budgeted_hours


h3 Department Managers

- if @department.department_managers.length == 0
  .alert.alert-error
    strong Warning!
    ' No Department Managers Assigned
  button.btn.btn-primary type="button" href="#assign_department_managers" data-toggle="modal" Assign Department Managers

- else
  table.table.table-bordered.table-striped
    thead
      tr
        th Name
        th Username
        th Actions
    tbody
      - @department.department_managers.each do |department_manager|
        tr
          td= department_manager.user.full_name
          td= department_manager.user.username
          td
            = link_to 'Unassign', admin_department_manager_path(department_manager), remote: true, method: :delete, data: { confirm: 'Are you sure?', type: :json }, class: 'unassign-department-manager btn btn-danger'

  button.btn.btn-primary type="button" href="#assign_department_managers" data-toggle="modal" Assign Department Managers

h3 Department Assistants

- if @department.department_assistants.length == 0
  .alert.alert-error
    strong Warning!
    ' No Department Assistants Assigned
  button.btn.btn-primary type="button" href="#assign_department_assistants" data-toggle="modal" Assign Department Assistants

- else
  table.table.table-bordered.table-striped
    thead
      tr
        th Name
        th Username
        th Actions
    tbody
      - @department.department_assistants.each do |department_assistant|
        tr
          td= department_assistant.user.full_name
          td= department_assistant.user.username
          td
            = link_to 'Unassign', admin_department_assistant_path(department_assistant), remote: true, method: :delete, data: { confirm: 'Are you sure?', type: :json }, class: 'unassign-department-assistant btn btn-danger'
            |&nbsp;
            = link_to "Restrict Access", show_modal_admin_department_assistant_path(department_assistant), class: "button btn btn-info", remote: true

  button.btn.btn-primary type="button" href="#assign_department_assistants" data-toggle="modal" Assign Department Assistants

= render "assign_department_managers_modal", department_managers: @department_managers

= render "assign_department_assistants_modal", department_assistants: @department_assistants

app/views/admin/departments/update.js.erb
// Select the elements for re-use
$modal = $('.edit-modal');
$body = $modal.find('.modal-body');

// Remove any past alerts and put a new alert in
$body.find('.alert').remove();
$body.append('<div class="alert alert-success"><p>Changes saved! You may now close this window.</p></div>');

window.adminDepartmentTable.fnDraw();