config/routes.rb
VolunteerTracker::Application.routes.draw do

  # PUBLIC FACING
  resources :departments, only: [:index, :show]
  resources :charities, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }

  resources :users, only: [:edit] do
    resources :user_availabilities, only: [:index, :create, :destroy]
    resources :subaccounts do
      post :import, on: :collection
    end
  end

  get '/welcome' => 'welcome#index'

  namespace :admin do
    resources :users
    resources :charities
    resources :departments
    resources :events
    resources :organisations
    resources :department_managers
    resources :department_assistants do
      member { post :restrict_blocks }
      member { get :show_modal }
    end
    root to: 'base#index'
  end

  resources :dashboard, only: [:index, :registration_complete]
  namespace :dashboard do
    # VIEWING ONLY
    resources :departments, only: [:show, :edit] do
      member do
        get :for_promote
        get :assistants
      end
    end
    resources :user_charities

    # ROLES
    resources :department_assistants, only: [:create, :destroy, :restrict]
    resources :volunteer_managers, only: [:create, :destroy]
    resources :users

    # TIME RELATED
    resources :days
    resources :users do
      resources :user_availabilities
      resources :user_charities
    end
    resources :user_availabilities
    resources :department_blocks

    resources :user_schedules do
      get :dymo, on: :member
    end


    resources :become_users do
      collection do
        get :accept_transfer
        get :decline_transfer
        get :get_user_list
      end
    end

    resources :events do
      get :calendar, on: :collection
    end

    resources :check_ins do
      collection do
        get :scheduled
        get :manage
        get :active
        get :inactive
        get :fastpass
        get :manage
        put :update_batch
        post :create_batch
        post :is_accessible
      end
    end
    get 'volunteers/:year/:month/:day' => 'volunteers#index'

    get 'check_ins/scheduled/:day_id' => "check_ins#scheduled"
    get 'check_ins/active/:day_id' => "check_ins#active"
    get 'check_ins/inactive/:day_id' => "check_ins#inactive"

    get 'volunteers/:day_id' => "volunteers#index", as: :volunteers

    get 'check_outs/fastpass' => "check_ins#fastpass_out", as: :fastpass_check_out
    post 'check_outs' => "check_ins#check_out", as: :check_out

    resources :flags

    get 'department_blocks/:id/copy/' => 'department_blocks#copy'
    get 'departments/:id/export/:year/:month/:day' => 'department_blocks#export'
    get 'departments/:id/schedule/:year/:month/:day' => 'departments#schedule'
  end

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :root
    end
  end
end

app/controllers/subaccounts_controller.rb
class SubaccountsController < ApplicationController
  before_filter :authenticate_user!

  def index
    respond_to do |format|
      format.html
      format.json { render json: SubaccountDatatable.new(view_context, { user: current_user }) }
    end
  end

  def show
    @subaccount = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subaccount }
    end
  end

  def new
    @subaccount = current_user.subaccounts.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subaccount }
      format.js
    end
  end

  def edit
    @subaccount = current_user.subaccounts.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subaccount }
    end
  end

  def create
    @subaccount = current_user.subaccounts.new(params[:user])
    @subaccount.skip_confirmation!
    respond_to do |format|
      if @subaccount.save
        format.html { redirect_to user_subaccount_path(current_user, @subaccount), flash: { success: 'Subaccount was successfully created.' } }
        format.json { render json: @subaccount, status: :created, location: @subaccount }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @subaccount.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  def update
    @subaccount = current_user.subaccounts.find(params[:id])
    @subaccount.skip_reconfirmation!
    respond_to do |format|
      if @subaccount.update_attributes(params[:user])
        format.html { redirect_to user_subaccount_path(current_user, @subaccount), flash: { success: 'Subaccount was successfully updated.' } }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @subaccount.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subaccount = User.find(params[:id])
    @subaccount.destroy

    respond_to do |format|
      format.js
      format.html { redirect_to user_subaccounts_url(current_user) }
      format.json { head :no_content }
    end
  end

  def import
    service = Subaccounts::Importer.new(as: current_user)
    @response = service.import(params)

    if @response.not_valid_rows.present?
      flash.now[:alert] = 'We need a few corrections from you in order to fully import your list...'
    elsif @response.errors.present?
      redirect_to user_subaccounts_url(current_user), flash: { error: "#{@response.errors.join(' ,')}" }
    else
      redirect_to user_subaccounts_url(current_user), flash: { success: "#{@response.created_count} subaccounts imported." }
    end
  end

end

app/views/subaccounts/_form.html.slim
= simple_form_for([current_user, @subaccount], url: @subaccount.persisted? ? :user_subaccount : :user_subaccounts, html: { id: "new_subaccount", class: 'form-horizontal', method: @subaccount.persisted? ? :put : :post }) do |f|
  .col-sm-8.col-sm-offset-2
    = f.hidden_field :master_id, value: current_user.id
    = f.input :first_name
    = f.input :last_name
    = f.input :username
    = f.input :email, label: "Email notifications to:"
    = f.input :adult
    = f.input :cell_phone
    = f.input :home_phone
    = f.association :charities, collection: Charity.order('name'), as: :select, input_html: { multiple: false, size: 1 }, include_blank: false
    = f.input :tshirt_size, collection: User::TSHIRT_SIZES
    = f.hidden_field :organisation_id, value: Organisation.first.try(:id)
    .form-group
      .col-sm-9.col-sm-offset-3
        = f.button :submit, class: 'btn btn-primary'
        = link_to 'Back', user_subaccounts_path(current_user), class: 'btn btn-link'

app/views/subaccounts/_import_errors_list.html.slim
.subaccount-error-list
  = form_tag import_user_subaccounts_path(current_user) do
    table.table.table-bordered.table-striped
      tr
        th Username
        th Name
        th Email
        th User Charity
        th Availability
        th
        - rows.each_with_index do |row_with_errors, index|
          tr
            td
              = hidden_field_tag "data[#{index}][0]", row_with_errors[:row][0]
              = hidden_field_tag "data[#{index}][1]", row_with_errors[:row][1]
              = hidden_field_tag "data[#{index}][3]", row_with_errors[:row][3]
              = hidden_field_tag "data[#{index}][4]", row_with_errors[:row][4]
              = hidden_field_tag "data[#{index}][5]", row_with_errors[:row][5]
              = hidden_field_tag "data[#{index}][6]", row_with_errors[:row][6]
              = hidden_field_tag "data[#{index}][8]", row_with_errors[:row][8]
              - if row_with_errors[:errors][:username].present?
                = "#{row_with_errors[:row][2]} - #{row_with_errors[:errors][:username].join(', ')}"
                br
                = text_field_tag "data[#{index}][2]"
              - else
                = row_with_errors[:row][2]
                = hidden_field_tag "data[#{index}][2]", row_with_errors[:row][2]
            td
              = row_with_errors[:row][0]
              br
              = row_with_errors[:row][1]
            td
              - if row_with_errors[:errors][:email].present?
                = "#{row_with_errors[:row][5]} - #{row_with_errors[:errors][:email].join(', ')}"
                br
                = text_field_tag "data[#{index}][5]"
              - else
                = row_with_errors[:row][5]
                = hidden_field_tag "data[#{index}][5]", row_with_errors[:row][5]
            td
              - if row_with_errors[:errors][:charity].present?
                = row_with_errors[:errors][:charity]
                br
                = select_tag "data[#{index}][7]", options_from_collection_for_select(Charity.order(:name), :name, :name)
              - else
                = row_with_errors[:row][7]
                = hidden_field_tag "data[#{index}][7]", row_with_errors[:row][7]
            td
              - if row_with_errors[:errors][:abilities].present?
                = row_with_errors[:errors][:abilities]
                br
                = render "set_availabilities_dialog", index: index
                button.btn.btn-primary.open-set-availabilities-dialog type="button" href="#set_subaccount_availabilities_#{index}" data-toggle="modal" Set availabilities
              - else
                -(9..20).each do |n|
                  = hidden_field_tag "data[#{index}][#{n}]", row_with_errors[:row][n]
                ' set to go!
            td
              = link_to 'Delete', "#", class: "delete-row-with-errors"
    = submit_tag "Save", class: "btn btn-success right-floated-btn"

coffee:
  $ ->
    $(document).on "click", ".delete-row-with-errors", (e)->
      $(e.target).parents("tr").fadeOut().queue(->
        $(this).remove())
      false

app/views/subaccounts/_list.html.slim
.page-header
  h1 Subaccounts List

.row
  .col-sm-12.subaccounts-import-form
    = link_to 'New Subaccount', new_user_subaccount_path(current_user), class: 'btn btn-primary', remote: true
    = link_to 'Import Subaccounts', "#import-modal", class: 'btn btn-primary', "data-toggle" => "modal"

table.table.table-bordered.table-striped#subaccounts_list_table data-source=(user_subaccounts_url(current_user, format: :json))
  thead
    tr
      th Username
      th Name
      th User Charity
      th
      th
      th
  tbody
= render "subaccounts/import_subaccount_modal"
= render "shared/modal"

coffee:
  $ ->
    unless $.fn.dataTable.isDataTable('#subaccounts_list_table')
      $('#subaccounts_list_table').dataTable
        processing: true
        serverSide: true
        ajax: $('#subaccounts_list_table').data('source')
        lengthMenu: [[10, 25, 50, 99999], [10, 25, 50, "All"]]
        dom: '<\'clear\'><\'row\'<\'col-sm-5\'l><\'col-sm-7\'fT>>' + '<\'row\'<\'col-sm-12\'tr>>' + '<\'row\'<\'col-sm-5\'i><\'col-sm-7\'p>>'
        columnDefs: [
          targets: [ -1, -2 , -3]
          sortable: false
        ]
        pagingType: 'full_numbers'
        tableTools:
          sRowSelect: 'os'
          sSwfPath: "//cdn.datatables.net/tabletools/2.2.4/swf/copy_csv_xls_pdf.swf"
          aButtons: [
            {
              sExtends:     'collection'
              sButtonText:  'Save clipboard to / CSV / PDF'
              aButtons:     [ 
                { sExtends: 'copy', mColumns: 'sortable' }
                { sExtends: 'csv', mColumns: 'sortable', sFileName: "subaccounts-#{window.currentDate()}.csv" }
                { sExtends: 'xls', mColumns: 'sortable', sFileName: "subaccounts-#{window.currentDate()}.csv" }
                { sExtends: 'pdf', mColumns: 'sortable', sFileName: "subaccounts-#{window.currentDate()}.pdf" }
              ]
            }
            {
              sExtends:     'print'
            }
          ]

app/views/subaccounts/_new_form.html.slim
= simple_form_for([current_user, subaccount], url: subaccount.persisted? ? :user_subaccount : :user_subaccounts, html: { id: "new_subaccount", class: 'form-horizontal clearfix', method: subaccount.persisted? ? :put : :post }) do |f|
  .col-sm-8.col-sm-offset-2
    = f.hidden_field :master_id, value: current_user.id
    = f.input :first_name
    = f.input :last_name
    = f.input :username
    = f.input :email, label: "Email notifications to:"
    = f.input :adult
    = f.input :cell_phone
    = f.input :home_phone
    = f.association :charities, collection: Charity.order('name'), as: :select, input_html: { multiple: false, size: 1 }, include_blank: false
    = f.input :tshirt_size, collection: User::TSHIRT_SIZES
    = f.hidden_field :organisation_id, value: Organisation.first.try(:id)
    .form-group
      .col-sm-9.col-sm-offset-3
        = f.button :submit, class: 'btn btn-primary'

app/views/subaccounts/_set_availabilities_dialog.html.slim
.modal.fade id="set_subaccount_availabilities_#{index}"
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal"
          ' &times;
        h3 Set subaccount's availabilities
      .modal-body
        div.days-list-wrapper
          ul.days-list
            - Day.order(:date).each.with_index(9) do |day, i|
              li
                = label_tag "data[#{index}][#{i}]", day.long_date
                = check_box_tag "data[#{index}][#{i}]"

          button#set_availabilities.btn.btn-success.right-floated-btn type="button" data-dismiss="modal" Save

app/views/subaccounts/create.js.erb
// Select the elements for re-use
$modal = $('.edit-modal');
$body = $modal.find('.modal-body');

// Remove any past alerts and put a new alert in
$body.find('.alert').remove();
$body.append('<div class="alert alert-success"><p>New Subaccount created! You may now close this window.</p></div>');

app/views/subaccounts/destroy.js.erb
$("#<%= @subaccount.id %>-subaccount").parents("tr").fadeOut().queue(function() {
  $(this).remove();
})

app/views/subaccounts/import.html.haml
= render 'import_errors_list', rows: @response.not_valid_rows if @response.status == :error
= render 'list', subaccounts: @subaccounts

app/views/subaccounts/import.html.slim
- if @response.not_valid_rows.present?
	= render 'import_errors_list', rows: @response.not_valid_rows 
= render 'list'

app/views/subaccounts/index.html.haml
= render 'list', subaccounts: @subaccounts

app/views/subaccounts/index.html.slim
= render 'list'

app/views/subaccounts/new.html.slim
.page-header
  h1 Create a subaccount

= render 'form'

app/views/subaccounts/new.js.erb
//  Select the elements for re-use
$modal = $('.edit-modal');
$title = $modal.find('.modal-title');
$body = $modal.find('.modal-body');

// Set the title of the modal to an instance-relevant title
title = 'New Subaccount';

// Set the modal's title and body to the above values
$title.html(title);
$body.html("<%= escape_javascript(render partial: 'new_form', locals: { subaccount: @subaccount}) %>");

// Hide the submit button (it'd be a duplicate) and make the form remote
$body.find('input[type="submit"]').hide();
$body.find('form').attr('data-remote', 'true');

// Display the modal
$modal.modal();

app/views/subaccounts/show.html.slim
.page-header
  h1 = @subaccount.username

h3 Subaccount: #{@subaccount.full_name}

= link_to 'Back', user_subaccounts_path(current_user), class: 'btn btn-link'