config/routes.rb
VolunteerTracker::Application.routes.draw do

  # PUBLIC FACING
  resources :departments, only: [:index, :show]
  resources :charities, only: [:index, :show]

  devise_for :users, controllers: {
    registrations: 'registrations',
    sessions: 'sessions',
    passwords: 'passwords'
  }

  resources :users, only: [:edit] do
    resources :user_availabilities, only: [:index, :create, :destroy]
    resources :subaccounts do
      post :import, on: :collection
    end
  end

  get '/welcome' => 'welcome#index'

  namespace :admin do
    resources :users
    resources :charities
    resources :departments
    resources :events
    resources :organisations
    resources :department_managers
    resources :department_assistants do
      member { post :restrict_blocks }
      member { get :show_modal }
    end
    root to: 'base#index'
  end

  resources :dashboard, only: [:index, :registration_complete]
  namespace :dashboard do
    # VIEWING ONLY
    resources :departments, only: [:show, :edit] do
      member do
        get :for_promote
        get :assistants
      end
    end
    resources :user_charities

    # ROLES
    resources :department_assistants, only: [:create, :destroy, :restrict]
    resources :volunteer_managers, only: [:create, :destroy]
    resources :users

    # TIME RELATED
    resources :days
    resources :users do
      resources :user_availabilities
      resources :user_charities
    end
    resources :user_availabilities
    resources :department_blocks

    resources :user_schedules do
      get :dymo, on: :member
    end


    resources :become_users do
      collection do
        get :accept_transfer
        get :decline_transfer
        get :get_user_list
      end
    end

    resources :events do
      get :calendar, on: :collection
    end

    resources :check_ins do
      collection do
        get :scheduled
        get :manage
        get :active
        get :inactive
        get :fastpass
        get :manage
        put :update_batch
        post :create_batch
        post :is_accessible
      end
    end
    get 'volunteers/:year/:month/:day' => 'volunteers#index'

    get 'check_ins/scheduled/:day_id' => "check_ins#scheduled"
    get 'check_ins/active/:day_id' => "check_ins#active"
    get 'check_ins/inactive/:day_id' => "check_ins#inactive"

    get 'volunteers/:day_id' => "volunteers#index", as: :volunteers

    get 'check_outs/fastpass' => "check_ins#fastpass_out", as: :fastpass_check_out
    post 'check_outs' => "check_ins#check_out", as: :check_out

    resources :flags

    get 'department_blocks/:id/copy/' => 'department_blocks#copy'
    get 'departments/:id/export/:year/:month/:day' => 'department_blocks#export'
    get 'departments/:id/schedule/:year/:month/:day' => 'departments#schedule'
  end

  authenticated :user do
    root to: 'dashboard#index', as: :authenticated_root
  end
  unauthenticated do
    devise_scope :user do
      root to: 'devise/sessions#new', as: :root
    end
  end
end

app/controllers/dashboard/become_users_controller.rb
class Dashboard::BecomeUsersController < DashboardController

  def index
    respond_to do |format|
      format.html
      format.json { render json: BecomeUserDatatable.new(view_context) }
    end
  end

  def get_user_list
    respond_to do |format|
      format.json { render json: TransferUserDatatable.new(view_context) }
    end
  end

  def accept_transfer
    user = User.find(params[:user_id])

    subaccounts = User.where("pending_master_id = ?", user.id)

    if not subaccounts.blank?
      subaccounts.each do |subaccount|
        subaccount.master_id = user.id
        subaccount.pending_master_id = -1
        subaccount.save(validate: false)
      end
    end
    user.transfer_status = ""
    user.save(validate: false)

    redirect_to dashboard_index_path
  end

  def decline_transfer
    user = User.find(params[:user_id])
    subaccounts = User.where("pending_master_id = ?", @user.id)
    if not subaccounts.blank?
      subaccounts.each do |subaccount|
        subaccount.pending_master_id = -1
        subaccount.save(validate: false)
      end
    end
    @user.transfer_status = ""
    @user.save(validate: false)

    redirect_to dashboard_index_path
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.js
    end
  end

  def update
    @accounts_exist = false
    @master_user = params[:user][:master_id].present? ? User.find(params[:user][:master_id]) : nil
    @master_exists = @master_user.nil? ? false : true

    if @master_exists
      subaccount_ids = params[:user][:subaccount_ids]

      if not subaccount_ids.blank?
        subaccount_ids.each do |id|
          if not id.blank?
            @subaccount = User.find(id)
            if not @subaccount.blank?
              @accounts_exist = true

              @subaccount.pending_master_id = @master_user.id

              @subaccount.save(validate: false)
            end
          end
        end
      end

      if @accounts_exist
        @master_user.transfer_status = "PENDING"
        @master_user.save(validate: false)
      end
    end

    respond_to do |format|
        format.html { redirect_to dashboard_index_path, flash: { success: "Successfully began a transfer. The user must now accept the transfer."  } }
        format.json { head :no_content }
        format.js
    end

  end
end

app/controllers/dashboard/check_ins_controller.rb
class Dashboard::CheckInsController < DashboardController
  before_filter :volunteer_manager?, only: [:scheduled, :active, :inactive]
  before_filter :fastpass_acessible, only: [:fastpass, :fastpass_out]

  def show
    @check_in = CheckIn.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @check_in }
    end
  end

  def manage
  end

  def scheduled
    day = Day.find params[:day_id]
    respond_to do |format|
      format.html
      format.json { render json: ScheduledVolunteerDatatable.new(view_context, { user: current_user, day: day }) }
    end
  end

  def active
    day = Day.find params[:day_id]
    respond_to do |format|
      format.html
      format.json { render json: ActiveVolunteerDatatable.new(view_context, { user: current_user, day: day }) }
    end
  end

  def inactive
    day = Day.find params[:day_id]
    respond_to do |format|
      format.html
      format.json { render json: InactiveVolunteerDatatable.new(view_context, { user: current_user, day: day }) }
    end
  end

  def new
    @check_in = CheckIn.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @check_in }
    end
  end

  def edit
    @check_in = CheckIn.find(params[:id])
  end

  def fastpass
    @check_in = CheckIn.new
  end

  def fastpass_out
  end

  def check_out
    service = CheckInsService.new(as: current_user)
    @check_in = service.check_out(check_in_params[:user_schedule_id])

    if @check_in.is_a? String
      render json: { errors: [*@check_in] }
    else
      broadcast @check_in, 'check_out'
      render json: { user_data: FastPassPresenter.new.for_json(@check_in) }
    end
  end

  def is_accessible
    service = CheckInsService.new(as: current_user)
    render json: { status: :success, response: service.resourse_is_accessible_for_accessor(params[:id]) }
  end

  def create
    service = CheckInsService.new(as: current_user, fastpass: params[:fastpass].present?)
    @check_in = service.create(check_in_params)
    anchor = cookies.delete(:tabs_anchor)
    back_path = (request.referer && anchor) ? request.referer + '#' + anchor : :back

    respond_to do |format|
      if @check_in.present? && @check_in.persisted?
        broadcast @check_in, 'check_in'

        format.html { redirect_to back_path, flash: { success: 'Check in was successfully created.' } }
        format.json { render json: { user_data: FastPassPresenter.new.for_json(@check_in) } }
      else
        format.html { redirect_to back_path, flash: { error: @check_in.errors.values.join(', ') } }
        format.json { render json: { errors: FastPassPresenter.new.errors_for_json(@check_in) } }
      end
    end
  end

  def update
    service = CheckInsService.new(as: current_user)
    @check_in = service.update(params[:id], check_in_params)
    anchor = cookies.delete(:tabs_anchor)
    back_path = (request.referer && anchor) ? request.referer + '#' + anchor : :back

    respond_to do |format|
      if @check_in.errors.empty?
        broadcast @check_in, 'check_out'

        format.html { redirect_to back_path, flash: { success: 'Check in was successfully updated.' } }
        format.js { render 'successfully_updated' }
        format.json { head :no_content }
      else
        format.html { redirect_to back_path, flash: { error: @check_in.errors.values.join(', ') } }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_batch
    service = CheckInsService.new(as: current_user, fastpass: params[:fastpass].present?)
    check_in_params[:user_schedule_id].split(',').each do |item|
      @check_in = service.create(user_schedule_id: item, status: check_in_params[:status])
      break if @check_in.errors.present?
      broadcast(@check_in, 'check_in') if @check_in.errors.empty?
    end
    anchor = cookies.delete(:tabs_anchor)
    back_path = (request.referer && anchor) ? request.referer + '#' + anchor : :back

    respond_to do |format|
      if @check_in.present? && @check_in.persisted?
        format.html { redirect_to back_path, flash: { success: 'Check ins was successfully created.' } }
        format.json { render json: { user_data: FastPassPresenter.new.for_json(@check_in) } }
      else
        format.html { redirect_to back_path, flash: { error: @check_in.errors.values.join(', ') } }
        format.json { render json: { errors: FastPassPresenter.new.errors_for_json(@check_in) } }
      end
    end
  end

  def update_batch
    service = CheckInsService.new(as: current_user)
    check_in_params[:id].split(',').each do |item|
      @check_in = service.update(item, check_in_params)
      break if @check_in.errors.present?
      broadcast(@check_in, 'check_out') if @check_in.errors.empty?
    end
    anchor = cookies.delete(:tabs_anchor)
    back_path = (request.referer && anchor) ? request.referer + '#' + anchor : :back

    respond_to do |format|
      if @check_in.present? && @check_in.errors.empty?
        format.html { redirect_to back_path, flash: { success: 'Check ins was successfully updated.' } }
        format.js { render 'successfully_updated' }
        format.json { head :no_content }
      else
        format.html { redirect_to back_path, flash: { error: (@check_in ? @check_in.errors.values.join(', ') : 'Volunteers were not selected') } }
        format.json { render json: @check_in.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @check_in = CheckIn.find(params[:id])
    @check_in.destroy
    anchor = cookies.delete(:tabs_anchor)
    back_path = (request.referer && anchor) ? request.referer + '#' + anchor : :back

    respond_to do |format|
      format.html { redirect_to back_path }
      format.json { head :no_content }
    end
  end

  private

    def broadcast(obj, event_type)
      super "/channels/#{configatron.faye.channels.check_ins}", \
            { 
              event_type: event_type, 
              id: obj.id,
              data: VolunteerDatatable.new(view_context).html_row_from_record(obj)
            }
    end

    def volunteer_manager?
      redirect_to :root unless current_user.has_any_role? :volunteer_manager, :super_admin, :org_admin, :event_admin, :department_manager, :department_assistant
    end

    def fastpass_acessible
      redirect_to :root unless can?(:manage_fastpass, current_user)
    end

    def check_ins_service
      @service ||= CheckInsService.new(as: current_user)
    end

    def check_in_params
      params.require(:check_in).permit!
    end
end

app/controllers/dashboard/days_controller.rb
class Dashboard::DaysController < DashboardController

  def index
    @days = Day.all
    respond_to do |format|
      format.json { render json: @days.map { |day| {id: day.id, name: day.long_date} } }
    end
  end

end

app/controllers/dashboard/department_assistants_controller.rb
class Dashboard::DepartmentAssistantsController < DashboardController

  def create
    @department_assistant = DepartmentAssistant.new(params[:department_assistant])

    respond_to do |format|
      if @department_assistant.save
        format.html { redirect_to [:dashboard, @department_assistant.department], flash: { success: 'Department Assistant was successfully created.' } }
        format.json { render json: @department_assistant, status: :created, location: @department_assistant }
      else
        format.html { render action: 'new' }
        format.json { render json: @department_assistant.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @department_assistant = DepartmentAssistant.find(params[:id])
    @department_assistant.destroy

    respond_to do |format|
      format.html { redirect_to [:dashboard, @department_assistant.department] }
      format.json { head :no_content }
    end
  end

  def restrict
    @department_assistant = DepartmentAssistant.find(params[:id])

    respond_to do |format|
      format.html { redirect_to [:dashboard, @department_assistant.department] }
      format.json { head :no_content }
    end
  end
end

app/controllers/dashboard/departments_controller.rb
class Dashboard::DepartmentsController < DashboardController
  DEFAULT_PER_PAGE = 10
  before_filter :prepare_scope, only: [:for_promote, :assistants, :edit]
  before_filter :load_department, only: [:assistants, :edit]

  def show
    service = DepartmentService.new
    select = OpenStruct.new(
      total_slots: true,
      estimate_hours: true,
      scheduled_count: true
    )

    @department = service.prepare_single(select, params[:id])
    @department_block = DepartmentBlock.new
    @volunteer_hours = service.volunteer_hours_progress(@department.id)
    @days = Day.all

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @department }
    end
  end

  def edit
    @department_assistant = DepartmentAssistant.new
    @users = service.users_for_promote(@scope)
    @department_assistants = service.assistans_for_assignment(@scope)
    @department_blocks = service.blocks_for_assignment(params[:id])
  end

  def for_promote
    @users = service.users_for_promote(@scope)
  end

  def assistants
    @assistants = service.assistans_for_assignment(@scope)
  end

  def schedule
    @department = Department.find(params[:id])
    @department_block = DepartmentBlock.new()
    @days = Day.all
    @day = Day.where("year = ? AND month = ? AND mday = ?", params[:year],params[:month],params[:day]).first
    render layout: false
  end

  private
    # TODO: implement via datatables
    def prepare_scope
      @scope = {
        per: (params[:per] || DEFAULT_PER_PAGE).to_i,
        page: (params[:page] || 1).to_i,
        order_name: params[:order_name],
        order_role: params[:order_role],
        q: params[:q]
      }
    end

    def service
      @service ||= DepartmentService.new(as: current_user)
    end

    def load_department
      @department = Department.find(params[:id])
    end
end

app/controllers/dashboard/events_controller.rb
class Dashboard::EventsController < DashboardController

  def calendar
    @events = Event.all
    respond_to do |format|
      format.html
      format.json { render json: @events }
    end
  end

end

app/helpers/dashboard/department_blocks_helper.rb
module Dashboard::DepartmentBlocksHelper
  def common_params(scope)
    common_params = {}
    common_params.merge!({per_page: scope.per_page}) if scope.per_page.present?
    common_params.merge!({charity: scope.charity}) if scope.charity.present?
    common_params.merge!({role: scope.role}) if scope.role.present?
    common_params.merge!({order_charity: scope.order_charity}) if scope.order_charity.present?
    common_params.merge!({order_role: scope.order_role}) if scope.order_role.present?
    common_params.merge!({order_name: scope.order_name}) if scope.order_name.present?
    common_params.merge!({order_email: scope.order_email}) if scope.order_email.present?
    common_params.merge!({q: scope.q}) if scope.q.present?
    common_params
  end
end

app/helpers/dashboard/departments_helper.rb
module Dashboard::DepartmentsHelper
  def get_estimated_hours(department_id)
    @department = Department.find(department_id)
    total = 0
    @department.department_blocks.each do |department_block|
      start_time = department_block.start_time.utc_date
      end_time = department_block.end_time.utc_date

      duration_in_minutes = (end_time.to_f - start_time) / 60 
      duration_in_hours = duration_in_minutes / 60

      if department_block.suggested_number_of_workers
        total += department_block.suggested_number_of_workers * duration_in_hours
      end
    end

    return total
  end


  def get_department_usage(estimated_hours, allocated_hours)
    if allocated_hours == 0
      return 100
    else
      return ( estimated_hours.to_f / allocated_hours.to_f ) * 100
    end
  end

  def get_department_usage_class(estimated_hours, allocated_hours)
    if estimated_hours.to_f > allocated_hours.to_f
      return "progress-bar-danger"
    else
      return ""
    end
  end
end

app/views/dashboard/department_blocks/_edit_form.html.slim
= form_for( @department_block, url: dashboard_department_block_path, html: { class: 'form-horizontal clearfix' } ) do |f|
  .col-sm-8.col-sm-offset-2
    - if @department_block.errors.any?
      #error_explanation
        h2= "#{pluralize(@department_block.errors.count, "error")} prohibited this department_block from being saved:"
        ul
          - @department_block.errors.full_messages.each do |msg|
            li= msg

    fieldset
      - if @department_block.department
        = f.hidden_field :department_id
      - else
        = f.hidden_field :department_id, value: @department.id
      .form-group
        = f.label(:name, class: 'control-label col-sm-3')
        .col-sm-9
          = f.text_field(:name, class: 'form-control')
      .form-group
        = f.label(:start_time, class: 'control-label col-sm-3')
        .col-sm-9
          .input-group.date.bootstrap-timepicker
            =f.text_field(:start_time, class: 'form-control', value: in_twelve_hour_time(@department_block.start_time))
            span.input-group-addon
              span.glyphicon.glyphicon-calendar
      .form-group
        = f.label(:end_time, class: 'control-label col-sm-3')
        .col-sm-9
          .input-group.date.bootstrap-timepicker
            =f.text_field(:end_time, class: 'form-control', value: in_twelve_hour_time(@department_block.end_time))
            span.input-group-addon
              span.glyphicon.glyphicon-calendar
      .form-group
        = f.label(:suggested_number_of_workers, class: 'control-label col-sm-3')
        .col-sm-9
          = f.number_field(:suggested_number_of_workers, class: 'form-control')
        .form-actions
          .col-sm-9.col-sm-offset-3
            = f.submit( class: 'btn btn-primary', value: "Save Changes" )

app/views/dashboard/department_blocks/_form.html.slim
= form_for(@department_block, :url => dashboard_department_blocks_path, :html => {:class => 'form-horizontal'}) do |f|
  .col-sm-8.col-sm-offset-2
    - if @department_block.errors.any?
      #error_explanation
        h2= "#{pluralize(@department_block.errors.count, "error")} prohibited this department_block from being saved:"
        ul
          - @department_block.errors.full_messages.each do |msg|
            li= msg

    fieldset
      - if @department_block.department
        = f.hidden_field :department_id
      - else
        = f.hidden_field :department_id, :value => @department.id
      .form-group
        = f.label(:name, :class => 'control-label col-sm-3')
        .col-sm-9
          = f.text_field(:name)
      .form-group
        = f.label(:start_time_id, :class => 'control-label col-sm-3')
        .col-sm-9
          = f.select(:start_time_id, EventTimeslot.all)
      .form-group
        = f.label(:end_time_id, :class => 'control-label col-sm-3')
        .col-sm-9
          = f.select(:end_time_id, time_list.collect {|time_list| [time_list[:readable_time], time_list[:time_slot_id]]})
      .form-group
        = f.label(:suggested_number_of_workers, :class => 'control-label col-sm-3')
        .col-sm-9
          = f.number_field(:suggested_number_of_workers)
      .form-group
        .col-sm-9.col-sm-offset-3
          = f.submit(:class => 'btn btn-primary', :value => "Save Changes")

app/views/dashboard/department_blocks/_pagination.html.haml
- if @show_action_data.scope.page > 1
  = link_to "Previous", dashboard_department_block_path(@show_action_data.department_block, common_params(@show_action_data.scope).merge({page: @show_action_data.scope.page - 1})), remote: true, class: "paginate_disabled_previous"
- if @show_action_data.user_availabilities_count > @show_action_data.scope.page * @show_action_data.scope.per_page
  = link_to "Next", dashboard_department_block_path(@show_action_data.department_block, common_params(@show_action_data.scope).merge({page: @show_action_data.scope.page + 1})), remote: true, class: "paginate_disabled_next"

app/views/dashboard/department_blocks/_pagination_info.html.slim
div Showing #{(@show_action_data.scope.page - 1) * @show_action_data.scope.per_page + 1} to #{@show_action_data.scope.page * @show_action_data.scope.per_page} of #{pluralize( @show_action_data.user_availabilities_count, 'entry')}

app/views/dashboard/department_blocks/show.html.slim
- suggested_number_of_workers = @show_action_data.department_block.suggested_number_of_workers

.col-sm-12
  ol.breadcrumb
    = render_breadcrumbs tag: :li, separator: ""

  .col-sm-9
    h3 Volunteer Managers

    - if @show_action_data.department_block.volunteer_managers.count == 0
      .alert.alert-error
        strong Warning!
        ' No Volunteer Managers Assigned
      button.btn.btn-primary type="button" href="#assign_volunteer_managers" data-toggle="modal" Assign Volunteer Managers

    - else
      table.table.table-bordered.table-striped
        thead
          tr
            th Name
            th Usernane
            th Actions
        tbody
        - @show_action_data.department_block.volunteer_managers.each do |volunteer_manager|
          tr
            td= volunteer_manager.user.full_name
            td= volunteer_manager.user.username
            td
              - if @show_action_data.volunteer_managers[volunteer_manager.user_id].present?
                = link_to 'Unassign', dashboard_volunteer_manager_path(@show_action_data.volunteer_managers[volunteer_manager.user_id]), data: { confirm: 'Are you sure?', type: :json }, class: 'unassign-volunteer-manager btn btn-danger'

      =link_to "Save and Return to Blocks", dashboard_department_path(@show_action_data.department_block.department, anchor: @show_action_data.department_block.day.safe_short_date), class: "btn btn-primary"
  .col-sm-3
    ul.list-group
      li.list-group-item
        = "Block name - #{@show_action_data.department_block.name}"
      li.list-group-item
        = "Date - #{@show_action_data.department_block.day.long_date}"
      li.list-group-item
        = "Start time - #{@show_action_data.department_block.start_time_12}"
      li.list-group-item
        = "End time - #{@show_action_data.department_block.end_time_12}"
  .clearfix

  h3 Scheduled Volunteers

  p
    b Current Volunteer Allocation:
    '
    - current_allocation = @show_action_data.department_block.users.count
    - if suggested_number_of_workers
      ="(#{current_allocation}/#{suggested_number_of_workers})"
    - else
      ="0/0"
  .progress
    - if suggested_number_of_workers
      .progress-bar class=(get_department_usage_class(current_allocation, suggested_number_of_workers)) style="width: #{get_department_usage(current_allocation.to_f, suggested_number_of_workers.to_f)}%;"
    - else
      .progress-bar.progress-bar-danger style="width: 100%;"


  table.table.table-bordered.table-striped.scheduled-user-table
    thead
      tr
        th Name
        th Username
        th Actions
    tbody
      - @show_action_data.department_block.users.each do |user|
        tr
          td= user.full_name
          td= user.username
          td
            - if @show_action_data.user_schedules[user.id].present?
              = link_to 'Unschedule', dashboard_user_schedule_path(@show_action_data.user_schedules[user.id]), data: { confirm: 'Are you sure?', type: :json }, class: 'unschedule-user btn btn-danger'
            |&nbsp;
            = link_to 'Print', dymo_dashboard_user_schedule_path(@show_action_data.user_schedules[user.id], format: :xml), class: "btn btn-info print-dymo-label"

  h3 Available Volunteers

  .dataTables_wrapper
    .dataTables_length
      label
        ' Show
        select#per_page size="1"
          option selected="selected" value="10" 10
          option value="25" 25
          option value="50" 50
          option value="100" 100
        ' entries
      .hidden
        = link_to "", "", remote: true, id: "hidden_link"
    .dataTables_filter
      label
        ' Search:
        input#search type="text" value=(@show_action_data.scope.q)
        = button_tag 'Search', id: "search_button"
    table.table.table-bordered.table-striped.schedule-user-table
      thead
        tr
          th.sortable.sorting type="name" Name
          th.sortable.sorting type="username" Username
          th Availability Time
          th User Schedules on Day
          th.sortable.sorting type="charity"
            = select_tag :charity, options_for_select([['All', '']] + Charity.order("name").all.map {|r| [r.name, r.id]}, @show_action_data.scope.charity)
            ' Charity
          th.sortable.sorting type="role"
            = select_tag :role, options_for_select([['All', '']] + Role::ROLES.map {|r| [r.humanize, r]}, @show_action_data.scope.role)
            ' Role
          th Actions
      tbody
        = render collection: @show_action_data.user_availabilities, partial: 'user_availability', locals: {department_block: @show_action_data.department_block}
    .dataTables_info
      = render "pagination_info"
    .dataTables_paginate.paging_two_button
      = render 'pagination'
  .pull-right
    =link_to "Save and Return to Blocks", dashboard_department_path(@show_action_data.department_block.department, anchor: @show_action_data.department_block.day.safe_short_date), class: "btn btn-primary"


#assign_volunteer_managers.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        button.close type="button" data-dismiss="modal" &times;
        h4.modal-title Assign Volunteer Managers
      .modal-body
        p Here is a list of potential volunteer managers that are already scheduled to this block.

        table.table.table-bordered.table-striped
          thead
            tr
              th Name
              th Assign as Volunteer Manager
          tbody
            - @show_action_data.department_block.users.each do |user|
              - if user.role == "volunteer_manager"
                tr
                  td= user.full_name
                  td
                    = simple_form_for [:dashboard, VolunteerManager.new], html: { data: { type: :json } } do |f|
                      = f.input :user_id, as: :hidden, input_html: { value: user.id }
                      = f.input :department_block_id, as: :hidden, input_html: { value: @show_action_data.department_block.id }

                      = f.button :submit, 'Assign', class: 'btn btn-success'

= render "shared/modal"

= javascript_include_tag "libs/DYMO.Label.Framework.latest.js"

javascript:
  $(function() {
    var loadData = function(el) {
      $this = $(el);
      $link = $('#hidden_link');
      $link.attr('href', window.location.pathname + prepare_query());
      $link.trigger('click');
    }
    $('#per_page, #charity, #role').on('change', function() {
      loadData(this);
    });

    $('#search').on('keyup', function(e) {
      if (e.keyCode == 13) {
        loadData(this);
      }
      return false;
    });

    $('#search_button').on('click', function(e) {
      loadData($('#search').val());
      return false;
    });

    $('#search').on('blur', function(e) {
      loadData(this);
      return false;
    });

    var prepare_query = function() {
      charity  = $('#charity').val();
      role     = $('#role').val();
      q        = $('#search').val();
      per_page = $('#per_page').val();

      result = "?per_page=" + per_page + "&charity=" + charity + "&role=" + role +
               "&q=" + q + "&order_email=" + window.sortings.order_email +
               "&order_username=" + window.sortings.order_username +
               "&order_name=" + window.sortings.order_name +
               "&order_role=" + window.sortings.order_role +
               "&order_charity=" + window.sortings.order_charity;
      return result;
    };


    window.sortings = {};
    $('th.sortable').on('click', function() {
      window.sortings = {};
      $this = $(this);
      type = $this.attr('type');

      $.each($('.sortable'), function(index, el) {
        $el = $(el);
        el_type = $el.attr('type');

        if (type != el_type) {
          $el.removeClass('sorting');
          $el.removeClass('sorting_asc');
          $el.removeClass('sorting_desc');
          $el.addClass('sorting');
        }
      });

      if ($this.hasClass('sorting')) {
        startSort($this);
      } else if ($this.hasClass('sorting_asc')){
        sortAsc($this);
      }else if ($this.hasClass('sorting_desc')){
        sortDesc($this);
      }
    });

    var startSort = function(el) {
      $this = $(el)
      column = $this.attr('type')
      window.sortings["order_" + column] = 'asc';
      $this.removeClass('sorting').addClass('sorting_asc');

      loadData($this);
      return false;
    };

    var sortAsc =  function(el) {
      $this = $(el)
      column = $this.attr('type')
      window.sortings["order_" + column] = 'desc';
      $this.removeClass('sorting_asc').addClass('sorting_desc');

      loadData($this);
      return false;
    };

    var sortDesc = function(el) {
      $this = $(el)
      column = $this.attr('type')
      window.sortings["order_" + column] = 'asc';
      $this.removeClass('sorting_desc').addClass('sorting_asc');

      loadData($this);
      return false;
    };
  });